/*
 * The MIT License
 *
 * Copyright 2025 Ricky☆.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package morse.gui;

import javax.swing.ImageIcon;

/**
 * Author: Ricky☆. 
 * Starting Date: 30/10/2025.
 * Ending Date: ??/11/2025.
 * Description: The following class represents the menu
 * where the end-user will interact with the app itself.
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        // Initialize the components
        initComponents();
        // Centralize the JFrame on the Screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPanel = new javax.swing.JTabbedPane();
        translatorPanel = new javax.swing.JPanel();
        translatedScrollPane = new javax.swing.JScrollPane();
        translatedTextPane = new javax.swing.JTextPane();
        toBeTranslatedScrollPane = new javax.swing.JScrollPane();
        toBeTranslatedTextPane = new javax.swing.JTextPane();
        modeButton = new javax.swing.JButton();
        translateButton = new javax.swing.JButton();
        fileChooserButton = new javax.swing.JButton();
        toBeTranslatedTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        translatedTitleLabel = new javax.swing.JLabel();
        currentImageLabel = new javax.swing.JLabel();
        arrowsImage = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        aboutScrollPane = new javax.swing.JScrollPane();
        aboutTextArea = new javax.swing.JTextArea();
        helpPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transcrypt");
        setIconImage(new ImageIcon(getClass().getResource("/images/mainIcon.png")).getImage());
        setResizable(false);

        translatedTextPane.setEditable(false);
        translatedTextPane.setFocusable(false);
        translatedScrollPane.setViewportView(translatedTextPane);

        toBeTranslatedScrollPane.setToolTipText("");
        toBeTranslatedScrollPane.setViewportView(toBeTranslatedTextPane);

        modeButton.setText("Change Mode");

        translateButton.setText("Translate");

        fileChooserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitFile.png"))); // NOI18N

        toBeTranslatedTitleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        toBeTranslatedTitleLabel.setForeground(new java.awt.Color(0, 255, 0));
        toBeTranslatedTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toBeTranslatedTitleLabel.setText("Natural Language");

        titleLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Morse Code Translator");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        translatedTitleLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        translatedTitleLabel.setForeground(new java.awt.Color(255, 0, 0));
        translatedTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        translatedTitleLabel.setText("Morse");

        currentImageLabel.setFocusable(false);
        currentImageLabel.setRequestFocusEnabled(false);
        currentImageLabel.setVerifyInputWhenFocusTarget(false);

        arrowsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/translationArrows.png"))); // NOI18N

        javax.swing.GroupLayout translatorPanelLayout = new javax.swing.GroupLayout(translatorPanel);
        translatorPanel.setLayout(translatorPanelLayout);
        translatorPanelLayout.setHorizontalGroup(
            translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(translatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toBeTranslatedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(translatorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arrowsImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(translatorPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(currentImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(translatedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(translatorPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(modeButton)
                .addGap(18, 18, 18)
                .addComponent(translateButton)
                .addGap(27, 27, 27)
                .addComponent(fileChooserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(translatorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toBeTranslatedTitleLabel)
                .addGap(26, 26, 26)
                .addComponent(titleLabel)
                .addGap(42, 42, 42)
                .addComponent(translatedTitleLabel)
                .addGap(102, 102, 102))
        );
        translatorPanelLayout.setVerticalGroup(
            translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, translatorPanelLayout.createSequentialGroup()
                .addGroup(translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, translatorPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(translatedTitleLabel))
                    .addGroup(translatorPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(toBeTranslatedTitleLabel))
                    .addGroup(translatorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel)))
                .addGroup(translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(toBeTranslatedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(translatedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(translatorPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(currentImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arrowsImage)))
                .addGap(15, 15, 15)
                .addGroup(translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileChooserButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, translatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(translateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        mainTabbedPanel.addTab("Translator", translatorPanel);

        aboutTextArea.setEditable(false);
        aboutTextArea.setColumns(20);
        aboutTextArea.setRows(8);
        aboutTextArea.setText("                                      Morse Code Translator\n\n-Purpose/Development of the App\n\nThis app pretends to translate natural language to morse code and\nvice-versa so any person, when in need of such tool, can do it \nwithout constraints of Network or Hardware.\n\n-How to use it?\n\nThis app is pretty simple to operate being that the user can either \nwrite himself the text or morse code that wants translated or can \nsubmit a text file to translate itself. Apart from that there is also the\noption to listen/see the message being transmited in real time.");
        aboutTextArea.setFocusable(false);
        aboutScrollPane.setViewportView(aboutTextArea);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(aboutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(aboutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        mainTabbedPanel.addTab("About", aboutPanel);

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        mainTabbedPanel.addTab("Help", helpPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabbedPanel)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabbedPanel)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JScrollPane aboutScrollPane;
    private javax.swing.JTextArea aboutTextArea;
    private javax.swing.JLabel arrowsImage;
    private javax.swing.JLabel currentImageLabel;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JTabbedPane mainTabbedPanel;
    private javax.swing.JButton modeButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JScrollPane toBeTranslatedScrollPane;
    private javax.swing.JTextPane toBeTranslatedTextPane;
    private javax.swing.JLabel toBeTranslatedTitleLabel;
    private javax.swing.JButton translateButton;
    private javax.swing.JScrollPane translatedScrollPane;
    private javax.swing.JTextPane translatedTextPane;
    private javax.swing.JLabel translatedTitleLabel;
    private javax.swing.JPanel translatorPanel;
    // End of variables declaration//GEN-END:variables
}
